### Login Request
# @name login
POST {{host}}/Auth_V2/UserLogin
Content-Type: application/json
Accept: application/json

## Request Body
{
  "UserName": "{{UserName}}",
  "Password": "{{EncryptedPassword}}",
  "RequestFrom":"{{RequestFrom}}"
}

### Set Token
@token = {{login.response.headers.Token}}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

### Get Loan List
# @name getLoanList
POST {{host}}/Loans_V1/GetLoanApplicationDetails
Content-Type: application/json
Accept: application/json
Token: {{token}}

## Request Body
{

  "LoanNumber": "D20240220106656",
  "ApplicationId": 106656,
  "RolePermissionId": "1,2,3",
  "UserId": "{{ByUserId}}",
  "UserName": "{{UserName}}",
  "UID": "{{ByUserId}}",
  "ByUserId": "{{ByUserId}}",
  "PersonId": "{{PersonId}}",
  "EmployeeCode": "{{EmployeeCode}}",
  "MobileNumber": "{{MobileNumber}}",
  "MobileNo": "{{MobileNumber}}",
  "RequestFrom":"{{RequestFrom}}"
}

### Response


